version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      #- ./:/code
      - static-data:/vol/web
      #- ./scripts/:/scripts
    env_file:
      - .env
    restart: always


  proxy:
    container_name: nginx
    build:
      context: ./nginx
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
      - 443:443
    volumes:
      - static-data:/vol/static
      - nginx-dhparams:/vol/nginx
    env_file:
      - .env


volumes:
  static-data:
  nginx-dhparams:
  mysql-data: